apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - /scripts/backup.sh
            image: ghcr.io/adfinis-adsygroup/openshift-etcd-backup
            imagePullPolicy: Always
            name: backup-etcd
            envFrom:
            - configMapRef:
                name: backup-config
            securityContext:
              privileged: true
              runAsUser: 0
            volumeMounts:
            - mountPath: /host
              name: host
            - name: volume-backup
              mountPath: /backup
          nodeSelector:
            node-role.kubernetes.io/master: ""
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
          hostNetwork: true
          hostPID: true
          serviceAccountName: etcd-backup
          restartPolicy: Never
          dnsPolicy: ClusterFirst
          volumes:
          - hostPath:
              path: /
              type: Directory
            name: host
          - name: volume-backup
            persistentVolumeClaim:
              claimName: etcd-backup-pvc
