---
# runs on each push to main and is responsible for creating new tags/releases
name: Create Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
        with:
          github-token: ${{ secrets.PAT }}
          allow-initial-development-versions: true
